model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
train_files:
  - ./data/video_r1_length_sft_1of3.jsonl
output_dir: ./outputs/qwen25vl3b_lora_sft_length
merge_output_dir: ./outputs/qwen25vl3b_lora_merged_length

max_length: 4096
val_size: 0.05
seed: 42

bf16: true
fp16: false

learning_rate: 2.0e-4
weight_decay: 0.0
warmup_ratio: 0.03
lr_scheduler_type: cosine
num_train_epochs: 1.0

per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 8

logging_steps: 10
save_steps: 200
eval_steps: 200
save_total_limit: 3
gradient_checkpointing: true
use_vision: true
max_visual_items: 16

lora_r: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target_modules: auto

sft_mode: length
reasoning_formats:
  - answer
  - cot
  - long_cot
format_mix_strategy: expand
append_format_instruction: true
drop_code_cot: true
